server:
  port: 8080
  servlet:
    context-path: /service
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/jwt_security
    username: root
    password: doquangduc123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MariaDBDialect
jwt:
  signerKey: "a7pyKXRBwRp3H+FkaOTmef0Q8sOpM42BePDRcMcs7VAZ81Qo4gy/ULxB3gBYL+Oy"
  valid-duration: 3600 #in second
  refreshable-duration: 3600 #in second